version: "3.7"

services:
  app:
    container_name: react-app-ui
    build:
      context: .
      dockerfile: ./app-ui.dockerfile
    ports:
      - "8080:3000"

  mock-api:
    container_name: mock-api-service
    build:
      context: ./mock-api
      dockerfile: ./mock-api.dockerfile
    restart: always
    ports:
      - "9100:80"
